vich_uploader:
    db_driver: orm

    mappings:
        program_image:
            uri_prefix: /images/program
            upload_destination: '%kernel.project_dir%/public/images/program'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true